apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ljykt1eyp-python
  janus-idp.io/tekton: ljykt1eyp-python
  backstage.io/kubernetes-id: ljykt1eyp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ljykt1eyp-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
